name: Daily Bonus

on:
  push:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    environment: checkin_environment

    env:
      BILIBILI_COOKIES: ${{ secrets.BILIBILI_COOKIES }}
      MUSIC_CELLPHONE: ${{ secrets.MUSIC_CELLPHONE }}
      MUSIC_PASSWORD: ${{ secrets.MUSIC_PASSWORD }}
      YAMIBO_COOKIES: ${{ secrets.YAMIBO_COOKIES }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check in
        run: |
          python ./Bilibili/bilibili_checkin.py
          python ./NetEase_Cloud_Music/music_checkin.py
          python ./Yamibo/yamibo_checkin.py