name: Daily Bonus

on:
  push:
  schedule:
    - cron: '30 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BILIBILI_COOKIES: ${{ secrets.BILIBILI_COOKIES }}
      MUSIC_CELLPHONE: ${{ secrets.MUSIC_CELLPHONE }}
      MUSIC_PASSWORD: ${{ secrets.MUSIC_PASSWORD }}
      YAMIBO_COOKIES: ${{ secrets.YAMIBO_COOKIES }}
      V2EX_COOKIES: ${{ secrets.V2EX_COOKIES }}

    steps:
      - uses: actions/checkout@v2
      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Echo current time
        run: timedatectl
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Bilibili
        run: |
          output=$(python ./Bilibili/bilibili_checkin.py)
          echo "BILIBILI=$output" >> $GITHUB_ENV
        if: always()
      - name: Yamibo
        run: |
          output=$(python ./Yamibo/yamibo_checkin.py)
          echo "YAMIBO=$output" >> $GITHUB_ENV
        if: always()
      - name: NetEase Cloud Music
        run: |
          output=$(python ./Music163/music_checkin.py)
          echo "MUSIC163=$output" >> $GITHUB_ENV
        if: always()
      - name: V2EX
        run: |
          output=$(python ./V2EX/v2ex_checkin.py)
          echo "V2EX=$output" >> $GITHUB_ENV
        if: always()
      - name: Send telegram notification
        run: python ./message.py
